Link Newsletter
iGEM-Aachen/wiki2021 pull request #529
Opened 2021-10-20 18:45 UTC by linaa0712

Newsletter verlinkt.
Text wird noch verändert, muss aber erstmal essen gehen.
Passt das mit dem code so ?

2021-10-20 18:52 UTC, anmaht requested changes

2021-10-20 18:52 UTC, anmaht commented on src/pages/Human_Practices.pug
> +        For the importants Months of May, June, August and September we created newsletters to inform our sponsors and supporters about our prgress.
```suggestion
        For the important months of May, June, August, and September we created newsletters to inform our sponsors and supporters about our progress.
```

2021-10-20 18:52 UTC, anmaht commented on src/pages/Human_Practices.pug
> +    a(href=pdfpath) Here you can find the lesson plan
Was ist das für ein Kommando? Ich kenne das nicht, also vllt ist es richtig, aber keine Ahnung, was du damit meinst :D

2021-10-21 09:41 UTC, clemenskoehler commented on src/pages/Human_Practices.pug
> +    - var pdfpath = "Newsletter September" + require("../assets/documents/communication/Newsletter_September.pdf")["default"]
```suggestion
    - var pdfpath = "" + require("../assets/documents/communication/Newsletter_September.pdf")["default"]
    a(href=pdfpath) Newsletter September
```

2021-10-21 10:24 UTC, merged